# Generated by Django 5.0.3 on 2024-04-04 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_insight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_row', models.CharField(max_length=100)),
                ('total_column', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('data_types', models.JSONField()),
                ('missing_values', models.JSONField()),
                ('unique_values', models.JSONField()),
                ('descriptive_statistics', models.JSONField()),
                ('data_quality_issues', models.JSONField()),
                ('correlation_coefficients', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_insight.project')),
            ],
            options={
                'db_table': 'testresult',
            },
        ),
    ]
