# Generated by Django 5.0.3 on 2024-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_insight', '0002_testrow_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pipeline',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
