# Generated by Django 5.0.3 on 2024-04-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_insight', '0005_remove_dataqualityissue_test_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiondetails',
            name='password',
            field=models.TextField(),
        ),
    ]
