# Generated by Django 5.0.3 on 2024-04-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_insight', '0007_alter_connectiondetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiondetails',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
