# Generated by Django 5.0.3 on 2024-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_insight', '0008_alter_connectiondetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='outliers',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
